server {
    listen 80;
    listen 443;

    server_name _;

    location / {
        proxy_pass http://n8n:5678;
        proxy_set_header Host $host;
        proxy_http_version 1.1; 
        proxy_set_header Upgrade $http_upgrade;  
        proxy_set_header Connection "upgrade";  
    }
}